# values-secret.yaml  <-- DO NOT COMMIT; add to .gitignore

studentApi:
  config:
    datasource:
      # real DB password for the app to connect to MySQL
      password: "REPLACE_WITH_REAL_APP_DB_PASSWORD"

studentDb:
  mysql:
    rootPassword: "REPLACE_WITH_REAL_ROOT_PASSWORD"
    password: "REPLACE_WITH_REAL_DB_USER_PASSWORD"
