---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespaces.studentApi }}
type: Opaque
stringData:
  DB_USERNAME: "{{ .Values.studentDb.mysql.user }}"
  DB_PASSWORD: "{{ .Values.studentDb.mysql.password }}"
  DB_NAME: "{{ .Values.studentDb.mysql.database }}"
  DB_HOST: "student-db.{{ .Values.namespaces.studentApi }}.svc.cluster.local"
