---
apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: {{ .Values.namespaces.studentApi }}
  labels:
    app: student-api
spec:
  selector:
    app: student-api
  ports:
    - port: {{ .Values.studentApi.service.port }}
      targetPort: {{ .Values.studentApi.service.targetPort }}
{{- if .Values.studentApi.service.nodePort }}
      nodePort: {{ .Values.studentApi.service.nodePort }}
{{- end }}
  type: {{ .Values.studentApi.service.type }}
