---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-db
  namespace: {{ .Values.namespaces.studentApi }}
  labels:
    app: student-db
spec:
  replicas: {{ .Values.studentDb.replicaCount }}
  selector:
    matchLabels:
      app: student-db
  template:
    metadata:
      labels:
        app: student-db
    spec:
{{- if .Values.studentDb.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.studentDb.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: mysql
          image: "{{ .Values.studentDb.image.repository }}:{{ .Values.studentDb.image.tag }}"
          imagePullPolicy: "{{ .Values.studentDb.image.pullPolicy }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.studentDb.mysql.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.studentDb.mysql.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.studentDb.mysql.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.studentDb.mysql.password }}"
          ports:
            - containerPort: {{ .Values.studentDb.containerPort }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: student-db-pvc
